##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  guns配置  ###################
guns:
  client-url: http://localhost:8088 #微信端地址

###################  wechat配置  ###################
wechat:
  xcx-appid: 1 #小程序appid
  xcx-secret: 1 #小程序secret
  appid: 1 #服务号appid
  secret: 1 #服务号secret

###################  项目启动端口  ###################
server:
  port: 8088

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false


###################  spring配置  ###################
spring:
  redis:
    host: localhost
    port: 6379
    password:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**


###################  beetl配置  ###################
dubbo:
  application-name: krvip.provider
  registry-address: 127.0.0.1:2181
  registry-protocol: zookeeper
  monitor-protocol: registry
  protocol-port: 20880

logging:
  level.root: warn
  level.com.ikoori: info
  path: logs/
  file: krvip.log
